add location context to logs that fail format
example:
```
Error: /root/git/cdefmt/examples/stdout-cpp/main.cpp:212: Could not format 'Wrong named parameters: {asome_f32} {some_struct.ba} {1} {some_u16} {}'

Caused by:
    Named parameter requested (asome_f32) but not provided
```